# --- Tabela convertida para comentários (versão atual) ---
# | Nome da coluna       | Termo                            | Unidade        | Definição prática                                                      | Observações                                                 |
# | -------------------- | -------------------------------- | -------------- | ---------------------------------------------------------------------- | ----------------------------------------------------------- |
# | Area_ha              | Área (A)                         | ha             | Área total da linha de cálculo.                                        | Usada para dimensionar a área efetiva após perdas.          |
# | Perc_Manobra_%       | Perdas por manobra/bordadura (B) | %              | Percentual de área não efetiva devido a bordaduras, curvas e manobras. | Configurar por processo/talhão conforme realidade local.    |
# | Perc_Trafego_%       | Perdas por tráfego (C)           | %              | Percentual de área não efetiva devido ao tráfego/compactação.          | Depende de umidade do solo, pneus, CTF e logística.         |
# | Variedade            | Variedade (D)                    | —              | Cultivar da cana-de-açúcar (RB…, CTC…).                                | Define parâmetros via lookup na aba Parametros.             |
# | Epoca                | Época (E)                        | —              | Condição sazonal: Chuva ou Seca.                                       | Controla G_final, tolerância de desvio e TCH de referência. |
# | Processo             | Processo (F)                     | —              | Tipo de operação: Manual ou Mecanizado.                                | Afeta a viabilidade operacional (fator por processo).       |
# | E                    | Espaçamento entre linhas (E)     | m              | Distância entre linhas de plantio.                                     | Define os metros de linha por hectare: 10.000/E.            |
# | G_final              | Meta de gemas viáveis (G_final)  | gemas/m        | Número-alvo de gemas viáveis por metro de linha.                       | Aumenta na seca; base da dose de muda.                      |
# | s                    | Gemas por tolete (s)             | gemas/tolete   | Gemas totais por tolete.                                               | Junto com Q, valida a deposição total de gemas.             |
# | g_to                 | Gemas viáveis por tolete (g_to)  | viáveis/tolete | Número de gemas viáveis por tolete.                                    | Usado para calcular Q (toletes/m) e a dose-alvo.            |
# | L_to                 | Comprimento do tolete (L_to)     | m              | Comprimento de cada tolete.                                            | Normalmente padronizado (ex.: 0,40 m).                      |
# | rho                  | Densidade linear do colmo (ρ)    | kg/m           | Massa por metro de colmo.                                              | Pode variar por variedade/classe de colmo.                  |
# | d_rec_kg_m           | Dose alvo por metro (O)          | kg/m           | Dose técnica recomendada por metro.                                    | Cálculo: (G_final/g_to) × L_to × ρ.                         |
# | m_linhas_por_ha      | Metros de linha por hectare (P)  | m/ha           | Quantidade de metros de linha em 1 ha.                                 | Cálculo: 10.000 / E.                                        |
# | toletes_por_m        | Toletes por metro (Q)            | toletes/m      | Quantidade de toletes depositados por metro.                           | Cálculo: G_final / g_to.                                    |
# | gemas_plantadas_m    | Gemas plantadas por metro (R)    | gemas/m        | Total de gemas depositadas por metro.                                  | Cálculo: Q × s.                                             |
# | toletes_por_ha       | Toletes por hectare (S)          | toletes/ha     | Total de toletes depositados por hectare.                              | Cálculo: Q × P.                                             |
# | Massa de muda (t/ha) | Massa de muda (T)                | t/ha           | Toneladas de muda utilizadas por hectare (não produtividade).          | Cálculo: (S × L_to × ρ) / 1000.                             |
# | d_equiv_kg_m         | Dose praticada por metro (U)     | kg/m           | Dose efetivamente praticada por metro.                                 | Em v13: usa fator de processo na viabilidade (opção 2).     |
# | Area_efetiva_ha      | Área efetiva (V)                 | ha             | Área útil após perdas de manobra e tráfego.                            | Cálculo: A × (1 − B% − C%).                                 |
# | massa_total_area_t   | Massa total na área (W)          | t              | Toneladas totais de muda para a área efetiva.                          | Cálculo: T × V.                                             |
# | TCH_estimado_t_ha    | TCH estimado                     | t/ha           | Produtividade estimada de colheita.                                    | Cálculo típico: TCH_ref × (1 − k × desvio).                 |
